prueba/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get '/bienvenida', to: 'home#index'

root to: 'home#index'

get 'articles', to: 'articles#index'
get 'articles/new', to: 'articles#new', as: :new_articles
get 'articles/:id', to: 'articles#show'
get 'articles/:id/edit', to: 'articles#edit'

patch 'articles/:id', to: 'articles#update', as: :article
post 'articles', to:'articles#create'
delete 'articles/:id', to: 'articles#destroy'
end

prueba/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

prueba/app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
end

prueba/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

prueba/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

prueba/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :find_article, except: [:new, :create, :index]
    before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destoy]

    def index
        @articles = Article.all
    end

    def show          
    end

    def new
        @article = Article.new
    end

    def edit
    end


    def update
        @article.update(title: params[:article][:title],content: params[:article][:content])
    redirect_to @article
    end


    def create
        @article = Article.create(title: params[:article][:title],content: params[:article][:content])
        render json:@article
    end

    def destroy
        @article.destroy 
        redirect_to root_path
    end


    def find_article
        @article = Article.find(params[:id])
    end

end

prueba/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

prueba/app/helpers/application_helper.rb
module ApplicationHelper
end

prueba/app/helpers/articles_helper.rb
module ArticlesHelper
end

prueba/app/helpers/home_helper.rb
module HomeHelper
end

prueba/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

prueba/app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
<div class="field">
<%= form.label :title %>
<%= form.text_field :title %>
</div>

<div class="field">
<%= form.label :content %>
<%= form.rich_text_area :content %>
</div>

<div class="field">
<%= form.submit%>
</div>
<%end%>

prueba/app/views/articles/edit.html.erb
<div class="small-container center-block">
<%= render "articles/form" %>
</div>

prueba/app/views/articles/index.html.erb
<div class="large-container center-block">
<h1 class="margin-top">Mis articulos</h1>

<% @articles.each do |article| %>
<div class="card margin-top padding">
    <h3 class="text-uppercase">
    <%= article.id%>
    <%= article.title%>
    </h3>
    <p class="text-secondary"><%= article.created_at%></p>
    <%= link_to  "Ver mas", article %>
</div> 
<%end%>
</div>

prueba/app/views/articles/new.html.erb
<div class="small-container center-block">
<%= render "articles/form" %>
</div>

prueba/app/views/articles/show.html.erb
<h1><%= @article.title%></h1>

<div>
<%=@article.content%>
</div>  

<div>
<%= link_to "Eliminar articulo", @article, method: :delete %>
</div>

prueba/app/views/home/index.html.erb
<h1>Hola <%= current_user.email%></h1>

prueba/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head> 
    <title>Prueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-primary"><%= notice %></p>
  <%end%>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <%end%>
  
    <%= render  "partials/nav" %>
    <%= yield %>
  </body>
</html>

prueba/app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
    <li class="nav-item">
        <%= link_to  "inicio", root_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to  "articulos", articles_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to  "nuevo", new_articles_path, class:"nav-link" %>
    </li>
<%if user_signed_in?%>
    <li class="nav-item">
        <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class:"nav-link" %>
    </li>
<%else%>
    <li class="nav-item">
        <%= link_to  "Iniciar Sesion", user_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to  "Registro", new_user_registration_path, class:"nav-link" %>
    </li>
<%end%>
</nav>